title: DrupalCamp Bristol 2015
subtitle: 3rd-4th July - Bristol, UK
dates: 3rd-4th July
twitter_url: http://www.twitter.com/DrupalCampBris
template: splash

sponsors:
  - name: Microserve
    link: http://www.microserveltd.co.uk
    logo: microserve.png
    level: 0
  - name: Sift Digital
    link: http://www.siftdigital.co.uk
    logo: sift-digital.png
    level: 0
  - name: Positive
    link: http://positivestudio.co.uk
    logo: positive.png
    level: 0

attendees:
  - name: test
    username: test
    link: https://drupal.org/u/opdavies
    photo:
    featured: true

committee:
  - name: Rick Donohoe
    org: Microserve
    drupalorg:
    twitter: 
    roles: Committee Chairman
  - name: Oliver Davies
    org: Drupal Association
    drupalorg: opdavies
    twitter: opdavies
    roles: Marketing, Website
  - name: Rich Saddington
    org: Sift Digital
    drupalorg:
    twitter: rsaddington
    roles:
  - name: Adrian Bateman
    org: Polynya
    drupalorg: 
    twitter: polynya_co_uk
    roles:
  - name: Emily Coward
    org: Nomensa
    drupalorg:
    twitter: emcoward
    roles:
  - name: Jon Hadley
    org: Positive
    drupalorg:
    twitter: mintsauce
    roles:
  - name: Mark Pavlitski
    org: Microserve
    drupalorg:
    twitter: markpavlitski
    roles:
  - name: Mike Dodd
    org: Mitkom Ltd
    drupalorg:
    twitter: Mitkom_uk
    roles:
  - name: Tom Metcalfe
    org: Black Label Web Design
    drupalorg:
    twitter: blwd_uk
    roles: