sculpin:
  permalink: pretty
  ignore:
    - '_examples/*'
    - '**/*.scss'
    - '**/config.rb'
    - '**/Gemfile*'
sculpin_content_types:
  posts:
    enabled: false
  speakers:
    permalink: speakers/:slug_title/
    enabled: false
  sponsors:
    permalink: sponsors/:slug_title/
  talks:
    permalink: talks/:slug_title/
    enabled: false
sculpin_theme:
  theme: drupalcampbristol/dcbristol2015